version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    ports:
      - 80:80
  
  frontend:
    restart: always
    volumes:
      - ./frontend:/usr/local/app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  strapi:
    image: strapi/strapi
    depends_on: 
      - mongo
    links:
      - mongo:mongo
    volumes:
      - ./app:/srv/app
    ports:
      - 1337:1337

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
