version: '3.7'
services:
  nginx:
    build: ./nginx/
    depends_on:
      - frontend
    ports:
      - 80:80
  
  frontend:
    working_dir: /usr/local/app
    restart: always
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/local/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - 3000:3000

  strapi:
    image: strapi/strapi
    depends_on: 
      - mongo
    links:
      - mongo:mongo
    # environment:
      # - NODE_ENV=production
    volumes:
      - ./app:/srv/app
    ports:
      - 1337:1337

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
